/**
 * Regenerates src/generated/<service>.ts from the per-service OpenAPI 3.0.3
 * specs at <repo root>/<service>-service/openapi.yaml, using a pinned
 * `npx --yes openapi-typescript@6` invocation per spec.
 *
 * Idempotent: each run fully overwrites the output files, so running it twice
 * in a row produces identical output.
 *
 * Usage: npm run generate
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const sdkRoot = path.resolve(here, "..");
const repoRoot = path.resolve(sdkRoot, "..", "..");

const services = [
  "accounts",
  "activities",
  "audit",
  "automation",
  "contacts",
  "integrations",
  "opportunities",
  "projects",
  "reporting",
  "search",
  "spend",
];

const outDir = path.join(sdkRoot, "src", "generated");
mkdirSync(outDir, { recursive: true });

const failures = [];

for (const service of services) {
  const specPath = path.join(repoRoot, `${service}-service`, "openapi.yaml");
  const outPath = path.join(outDir, `${service}.ts`);
  // The openapi-typescript@6 CLI resolves paths as URLs, which breaks on
  // absolute Windows paths (`d:` parses as a URL scheme). Always hand it
  // relative forward-slash paths with cwd at the SDK root.
  const specRel = path.relative(sdkRoot, specPath).split(path.sep).join("/");
  const outRel = path.relative(sdkRoot, outPath).split(path.sep).join("/");

  if (!existsSync(specPath)) {
    failures.push(`${service}: spec not found at ${specPath}`);
    continue;
  }

  console.log(`[generate] ${service}-service/openapi.yaml -> src/generated/${service}.ts`);
  const result = spawnSync(
    `npx --yes openapi-typescript@6 "${specRel}" --output "${outRel}"`,
    { cwd: sdkRoot, shell: true, stdio: ["ignore", "pipe", "pipe"], encoding: "utf8" },
  );

  if (result.status !== 0) {
    failures.push(
      `${service}: openapi-typescript exited with status ${result.status}\n${result.stderr || result.stdout || ""}`,
    );
    continue;
  }

  // Prepend a regeneration notice above the tool's own banner. The whole file
  // is rewritten on every run, so this stays idempotent.
  const header = [
    "/**",
    ` * Generated by openapi-typescript 6 from ${service}-service/openapi.yaml.`,
    " * Do not edit this file by hand: edit the source spec and re-run",
    " * `npm run generate` in sdks/typescript-sdk/.",
    " */",
    "",
  ].join("\n");
  const generated = readFileSync(outPath, "utf8");
  writeFileSync(outPath, header + generated);
}

if (failures.length > 0) {
  console.error("\n[generate] FAILED for:");
  for (const failure of failures) {
    console.error(`  - ${failure}`);
  }
  process.exit(1);
}

console.log(`\n[generate] OK: ${services.length} specs -> src/generated/`);
